#cloud-config
# Master Node - Cloud-Init Configuration
# Generated by Terraform - Do not edit manually

hostname: ${node_name}
fqdn: ${node_name}.local

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - nfs-common
  - net-tools

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - path: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--node-ip=${master_ip}

  - path: /tmp/kubeadm-init.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "node-role.kubernetes.io/control-plane="
      localAPIEndpoint:
        advertiseAddress: "${master_ip}"
        bindPort: 6443
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      kubernetesVersion: "${k8s_version}.0"
      controlPlaneEndpoint: "${vip_address}:6443"
      networking:
        podSubnet: "${pod_cidr}"
        serviceSubnet: "${service_cidr}"
        dnsDomain: "cluster.local"
      apiServer:
        certSANs:
          - "${vip_address}"
          - "${master_ip}"
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: "http://0.0.0.0:2381"

runcmd:
  # Kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # Disable swap
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  # Install CRI-O
  - echo "Installing CRI-O..."
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.opensuse.org/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v${k8s_version}/xUbuntu_24.04/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/cri-o.gpg] https://download.opensuse.org/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v${k8s_version}/xUbuntu_24.04/ /" > /etc/apt/sources.list.d/cri-o.list
  - apt-get update
  - apt-get install -y cri-o cri-o-runc
  - systemctl daemon-reload
  - systemctl enable crio --now

  # Install kubeadm, kubelet, kubectl
  - echo "Installing Kubernetes ${k8s_version}..."
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Install Helm
  - echo "Installing Helm..."
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # Pull images and init cluster (first master only)
  %{ if is_first }
  - kubeadm config images pull --config /tmp/kubeadm-init.yaml
  - kubeadm init --config /tmp/kubeadm-init.yaml --upload-certs | tee /tmp/kubeadm-init.log

  # Setup kubectl
  - mkdir -p /home/ubuntu/.kube
  - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown 1000:1000 /home/ubuntu/.kube/config

  # Install Calico CNI
  - kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml

  # Install Metrics Server
  - kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

  # Install MetalLB
  - helm repo add metallb https://metallb.github.io/metallb
  - helm install metallb metallb/metallb -n metallb-system --create-namespace

  # Install Kubernetes Dashboard
  - helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
  - helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard --create-namespace

  # Create dashboard service account with limited RBAC
  - |
    cat <<'DASHRBAC' | kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: admin-user
      namespace: kubernetes-dashboard
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: admin-user
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
    - kind: ServiceAccount
      name: admin-user
      namespace: kubernetes-dashboard
    DASHRBAC

  # Generate join commands for other nodes
  - kubeadm token create --print-join-command > /tmp/worker-join-command.txt
  - kubeadm init phase upload-certs > /tmp/cert-key.txt
  - kubeadm token create --certificate-key $(tail -1 /tmp/cert-key.txt) --print-join-command > /tmp/control-plane-join-command.txt

  # Store configs for Terraform to retrieve
  - cp /etc/kubernetes/admin.conf /tmp/kubeconfig
  - chmod 644 /tmp/kubeconfig
  %{ endif }
