#cloud-config
# Worker Node - Cloud-Init Configuration
# Generated by Terraform - Do not edit manually

hostname: ${node_name}
fqdn: ${node_name}.local

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - nfs-common
  - net-tools

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - path: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--node-ip=${worker_ip}

runcmd:
  # Kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # Disable swap
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  # Install CRI-O
  - echo "Installing CRI-O..."
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.opensuse.org/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v${k8s_version}/xUbuntu_24.04/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/cri-o.gpg] https://download.opensuse.org/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v${k8s_version}/xUbuntu_24.04/ /" > /etc/apt/sources.list.d/cri-o.list
  - apt-get update
  - apt-get install -y cri-o cri-o-runc
  - systemctl daemon-reload
  - systemctl enable crio --now

  # Install kubeadm, kubelet, kubectl
  - echo "Installing Kubernetes ${k8s_version}..."
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Label worker node (will be done after join from master)
  # Worker join is handled by the provisioner after cloud-init
