#!/bin/bash
# =============================================================================
# Common Bootstrap - Installs CRI-O, kubeadm, kubelet, kubectl
# Runs on ALL nodes (masters and workers)
# Generated by Terraform - Do not edit manually
# =============================================================================
set -euo pipefail

echo "==> [Common] Starting bootstrap for Kubernetes ${k8s_version}"

# Wait for cloud-init to fully finish (boot-finished is written before the
# final/fullcloud-init stages have run, so also wait for the process to exit
# to avoid clashing with cloud-init's own apt operations).
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
  echo "Waiting for cloud-init (boot-finished)..."
  sleep 5
done

while pgrep -f "cloud-init" >/dev/null 2>&1; do
  echo "Waiting for cloud-init to fully finish..."
  sleep 5
done

# Wrap apt so it waits up to 10 minutes for any in-flight apt/dpkg lock
# (e.g. cloud-init's own package operations) instead of failing immediately.
APTOPTS="-o DPkg::Lock::Timeout=600 -o Acquire::Lock::Timeout=600"
apt_get_update() {
  DEBIAN_FRONTEND=noninteractive apt-get $APTOPTS update -y
}
apt_get_install() {
  DEBIAN_FRONTEND=noninteractive apt-get $APTOPTS install -y "$@"
}

# Kernel modules
echo "==> Configuring kernel modules..."
cat <<'CHEOF' | tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
CHEOF

modprobe overlay
modprobe br_netfilter

# Sysctl parameters
cat <<'CHEOF' | tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
CHEOF

sysctl --system

# Disable swap
echo "==> Disabling swap..."
swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# Install required packages
echo "==> Installing base packages..."
apt_get_update
apt_get_install apt-transport-https ca-certificates curl gnupg lsb-release jq nfs-common net-tools conntrack

# Install CRI-O
echo "==> Installing CRI-O..."
mkdir -p /etc/apt/keyrings

curl -fsSL "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/${k8s_version}/deb/Release.key" \
  | gpg --dearmor -o /etc/apt/keyrings/cri-o.gpg

echo "deb [signed-by=/etc/apt/keyrings/cri-o.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/${k8s_version}/deb/ /" \
  > /etc/apt/sources.list.d/cri-o.list

apt_get_update
apt_get_install cri-o
systemctl daemon-reload
systemctl enable crio --now

# Setup root SSH access for cross-node communication (join scripts)
mkdir -p /root/.ssh
cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys

# Install Kubernetes components
echo "==> Installing kubeadm, kubelet, kubectl..."
curl -fsSL "https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/Release.key" \
  | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${k8s_version}/deb/ /" \
  > /etc/apt/sources.list.d/kubernetes.list

apt_get_update
apt_get_install kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

# Install Helm
echo "==> Installing Helm..."
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Configure kubelet with node IP
LOCAL_IP=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
cat > /etc/default/kubelet << EOF
KUBELET_EXTRA_ARGS=--node-ip=$LOCAL_IP
EOF

echo "==> [Common] Bootstrap completed successfully"
