#!/bin/bash
# =============================================================================
# Master Init - First Control Plane Node
# Generated by Terraform - Do not edit manually
# =============================================================================
set -euo pipefail

echo "==> [Master Init] Initializing first control plane"

# =============================================================================
# Step 1: Install kube-vip static pod for HA VIP
# =============================================================================
echo "==> [VIP/HA] Installing kube-vip..."

VIP_ADDRESS="${vip_address}"
K8S_VERSION="${k8s_version}.0"
KVVERSION="v1.1.2"

# Detect the primary network interface
NETWORK_INTERFACE=$(ip route show default | awk '{print $5}' | head -1)
echo "==> Detected network interface: $NETWORK_INTERFACE"

# Pre-pull kube-vip image so it starts immediately when kubelet picks up the manifest
echo "==> [VIP/HA] Pre-pulling kube-vip $${KVVERSION} image..."
crictl pull ghcr.io/kube-vip/kube-vip:$${KVVERSION} 2>&1 || echo "WARN: kube-vip image pull failed, will retry at runtime"

# Generate kube-vip static pod manifest (official ARP format)
mkdir -p /etc/kubernetes/manifests
cat > /etc/kubernetes/manifests/kube-vip.yaml << KVEOF
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: $${NETWORK_INTERFACE}
    - name: vip_subnet
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: address
      value: $${VIP_ADDRESS}
    image: ghcr.io/kube-vip/kube-vip:$${KVVERSION}
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
      readOnly: true
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/control-plane
  volumes:
  - hostPath:
      path: /etc/kubernetes/super-admin.conf
    name: kubeconfig
status: {}
KVEOF

echo "==> [VIP/HA] kube-vip manifest created with version $${KVVERSION}"

# =============================================================================
# Step 2: Pull Kubernetes images
# =============================================================================
echo "==> Pulling Kubernetes images..."
kubeadm config images pull --kubernetes-version "$${K8S_VERSION}" --cri-socket unix:///var/run/crio/crio.sock

# =============================================================================
# Step 3: Generate kubeadm config (controlPlaneEndpoint = VIP)
# =============================================================================
cat > /tmp/kubeadm-config.yaml << EOF
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
localAPIEndpoint:
  advertiseAddress: "${master_ip}"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: "$${K8S_VERSION}"
controlPlaneEndpoint: "$${VIP_ADDRESS}:6443"
networking:
  podSubnet: "${pod_cidr}"
  serviceSubnet: "${service_cidr}"
  dnsDomain: "cluster.local"
apiServer:
  certSANs:
    - "$${VIP_ADDRESS}"
    - "${master_ip}"
etcd:
  local:
    extraArgs:
      - name: listen-metrics-urls
        value: "http://0.0.0.0:2381"
EOF

# =============================================================================
# Step 4: Initialize cluster
# =============================================================================
echo "==> Running kubeadm init..."
kubeadm init --config /tmp/kubeadm-config.yaml --upload-certs 2>&1 | tee /tmp/kubeadm-init.log

# =============================================================================
# Step 5: Configure kubectl
# =============================================================================
echo "==> Configuring kubectl..."
mkdir -p /home/ubuntu/.kube
cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
chown 1000:1000 /home/ubuntu/.kube/config

mkdir -p /root/.kube
cp -f /etc/kubernetes/admin.conf /root/.kube/config

# Switch kube-vip from super-admin.conf to admin.conf (RBAC is now ready post-init)
echo "==> [VIP/HA] Switching kube-vip from super-admin.conf to admin.conf..."
sed -i 's|/etc/kubernetes/super-admin.conf|/etc/kubernetes/admin.conf|' /etc/kubernetes/manifests/kube-vip.yaml

# Wait for kubelet to restart kube-vip
echo "==> [VIP/HA] Waiting 20s for kube-vip to restart with admin.conf..."
sleep 20

# Verify VIP is up
echo "==> [VIP/HA] Verifying VIP $${VIP_ADDRESS}..."
VIP_UP=false
for i in $(seq 1 30); do
  if ip addr show $${NETWORK_INTERFACE} | grep -q "$${VIP_ADDRESS}"; then
    echo "==> [VIP/HA] VIP $${VIP_ADDRESS} is up on $${NETWORK_INTERFACE}"
    VIP_UP=true
    break
  fi
  sleep 2
done
if [ "$VIP_UP" != "true" ]; then
  echo "==> [VIP/HA] WARNING: VIP did not come up. Checking kube-vip status..."
  crictl ps | grep kube-vip || echo "kube-vip container not found"
fi

# =============================================================================
# Step 6: Install Calico CNI via Helm
# =============================================================================
echo "==> Installing Calico CNI..."

# Ensure DNS resolution works (systemd-resolved may be flaky before CNI)
echo "==> Configuring reliable DNS..."
# Fix systemd-resolved if needed
if [ -f /run/systemd/resolve/stub-resolv.conf ]; then
  sed -i 's/^#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf 2>/dev/null || true
  systemctl restart systemd-resolved 2>/dev/null || true
  sleep 3
fi

helm repo add projectcalico https://docs.tigera.io/calico/charts 2>/dev/null || true
helm repo update

# Retry Calico CRDs install (DNS may be flaky before CNI is ready)
echo "==> Installing Calico CRDs (with retry)..."
CRDS_OK=false
for i in $(seq 1 5); do
  if helm template calico-crds projectcalico/crd.projectcalico.org.v1 2>/dev/null | kubectl apply --server-side -f - 2>/dev/null; then
    echo "==> Calico CRDs installed successfully"
    CRDS_OK=true
    break
  fi
  echo "==> Calico CRDs attempt $i/5 failed, retrying in 10s..."
  sleep 10
done
if [ "$CRDS_OK" != "true" ]; then
  echo "ERROR: Failed to install Calico CRDs after 5 attempts"
  exit 1
fi

helm install calico projectcalico/tigera-operator \
  --namespace tigera-operator --create-namespace \
  --set installation.calicoNetwork.ipPools[0].cidr="${pod_cidr}" \
  --set installation.calicoNetwork.ipPools[0].encapsulation=VXLANCrossSubnet \
  --wait --timeout 10m

# =============================================================================
# Step 7: Install Metrics Server (with control-plane toleration)
# =============================================================================
echo "==> Installing Metrics Server..."
for i in $(seq 1 5); do
  curl -sL https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml -o /tmp/ms-components.yaml 2>/dev/null
  if [ -s /tmp/ms-components.yaml ]; then
    python3 -c "
import yaml
with open('/tmp/ms-components.yaml') as f:
    docs = list(yaml.safe_load_all(f))
for doc in docs:
    if doc and doc.get('kind') == 'Deployment':
        doc['spec']['template']['spec']['tolerations'] = [
            {'key': 'node-role.kubernetes.io/control-plane', 'operator': 'Exists', 'effect': 'NoSchedule'}
        ]
        containers = doc['spec']['template']['spec']['containers']
        for c in containers:
            if c.get('name') == 'metrics-server':
                args = c.get('args', [])
                if '--kubelet-insecure-tls' not in args:
                    args.append('--kubelet-insecure-tls')
                c['args'] = args
with open('/tmp/ms-tolerated.yaml', 'w') as f:
    yaml.dump_all(docs, f)
" && kubectl apply -f /tmp/ms-tolerated.yaml && echo "==> Metrics Server applied with control-plane tolerations" && break
  fi
  echo "==> Metrics Server attempt $i/5 failed, retrying in 10s..."
  sleep 10
done

# =============================================================================
# Step 8: Install MetalLB + IP Pool + L2 Advertisement
# =============================================================================
echo "==> Installing MetalLB..."
helm repo add metallb https://metallb.github.io/metallb 2>/dev/null || true
helm repo update
helm install metallb metallb/metallb -n metallb-system --create-namespace

# Wait for MetalLB controller and webhook to be ready
echo "==> Waiting for MetalLB controller..."

# First, patch the controller deployment to add control-plane tolerations
# (MetalLB helm chart doesn't include them by default, but our single-node master has the NoSchedule taint)
echo "==> Patching MetalLB controller tolerations for control-plane..."
kubectl patch deployment metallb-controller -n metallb-system \
  -p '{"spec":{"template":{"spec":{"tolerations":[{"key":"node-role.kubernetes.io/control-plane","operator":"Exists","effect":"NoSchedule"},{"key":"node-role.kubernetes.io/master","operator":"Exists","effect":"NoSchedule"}]}}}}' || echo "WARN: Could not patch controller tolerations"

# Wait for controller rollout
echo "==> Waiting for MetalLB controller rollout..."
kubectl rollout status deployment metallb-controller -n metallb-system --timeout=180s || echo "WARN: Controller rollout timeout"

# The speaker pod may be stuck waiting for the memberlist secret (created by controller).
# Delete it so it gets recreated with the secret available.
echo "==> Restarting MetalLB speaker pods to pick up memberlist secret..."
SPEAKER_PODS=$(kubectl get pods -n metallb-system -l app.kubernetes.io/component=speaker -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
if [ -n "$SPEAKER_PODS" ]; then
  for pod in $SPEAKER_PODS; do
    kubectl delete pod "$pod" -n metallb-system 2>/dev/null || true
  done
fi

# Wait for all MetalLB pods to be ready
echo "==> Waiting for all MetalLB pods to be ready..."
for i in $(seq 1 30); do
  NOT_READY=$(kubectl get pods -n metallb-system --no-headers 2>/dev/null | grep -v Running | grep -v Completed | head -1 || echo "")
  if [ -z "$NOT_READY" ]; then
    RUNNING=$(kubectl get pods -n metallb-system --no-headers 2>/dev/null | grep Running | wc -l)
    if [ "$RUNNING" -ge 2 ]; then
      echo "==> MetalLB is ready ($RUNNING pods running)"
      break
    fi
  fi
  echo "==> Waiting for MetalLB pods (attempt $i/30)..."
  sleep 10
done

# Extra wait for webhook to fully start
echo "==> Waiting 15s for MetalLB webhook to stabilize..."
sleep 15

# Apply IPAddressPool
echo "==> Applying MetalLB IPAddressPool (${metallb_ip_pool})..."
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - ${metallb_ip_pool}
EOF

# Apply L2Advertisement
echo "==> Applying MetalLB L2Advertisement..."
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool
EOF

echo "==> MetalLB configured with pool ${metallb_ip_pool}"

# =============================================================================
# Step 9: Install Kubernetes Dashboard v7.x
# =============================================================================
echo "==> Installing Kubernetes Dashboard v7.x..."

# Remove old repo if present, add new retired repo
helm repo remove kubernetes-dashboard 2>/dev/null || true
helm repo add kubernetes-dashboard https://kubernetes-retired.github.io/dashboard/
helm repo update kubernetes-dashboard

# Install Dashboard with CRDs, disable bundled nginx/cert-manager/ingress
# Add control-plane toleration so pods can schedule on tainted master node
helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard \
  --namespace kubernetes-dashboard --create-namespace \
  --set app.ingress.enabled=false \
  --set nginx.enabled=false \
  --set cert-manager.enabled=false \
  --set "app.tolerations[0].key=node-role.kubernetes.io/control-plane" \
  --set "app.tolerations[0].operator=Exists" \
  --set "app.tolerations[0].effect=NoSchedule" \
  --set "kong.tolerations[0].key=node-role.kubernetes.io/control-plane" \
  --set "kong.tolerations[0].operator=Exists" \
  --set "kong.tolerations[0].effect=NoSchedule" \
  --wait --timeout 10m || echo "WARN: Dashboard install failed (non-critical)"

# Expose Dashboard via LoadBalancer (MetalLB)
# Patch the existing kubernetes-dashboard-kong-proxy service to LoadBalancer
# (it already has correct selectors: app.kubernetes.io/name: kong + component: app)
echo "==> Exposing Dashboard via LoadBalancer..."
kubectl patch svc kubernetes-dashboard-kong-proxy -n kubernetes-dashboard \
  -p '{"spec":{"type":"LoadBalancer"}}' || echo "WARN: Could not patch Dashboard service to LoadBalancer"
echo "==> Dashboard exposed via kubernetes-dashboard-kong-proxy LoadBalancer"

# RBAC: ServiceAccount + cluster-admin binding
echo "==> Configuring Dashboard RBAC..."
cat <<'DASHEOF' | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
DASHEOF

# Generate long-lived token (1 year)
echo "==> Generating Dashboard access token..."
kubectl create token admin-user -n kubernetes-dashboard --duration=8760h > /tmp/dashboard-token.txt 2>/dev/null || true
echo "==> Dashboard token saved to /tmp/dashboard-token.txt"

# =============================================================================
# Step 10: Generate join commands
# =============================================================================
echo "==> Generating join commands..."
kubeadm token create --print-join-command > /tmp/worker-join-command.txt

# Generate a fresh certificate key and upload certs so additional control plane
# nodes can join with --control-plane. "kubeadm init phase upload-certs" alone
# does NOT produce the key (it exits with "Skipping phase"); we must generate
# one explicitly with "kubeadm certs certificate-key" and then upload it.
CERT_KEY=$(kubeadm certs certificate-key)
echo "==> Uploading control plane certificates with key $${CERT_KEY:0:8}..."
kubeadm init phase upload-certs --upload-certs --certificate-key "$CERT_KEY" 2>&1 | tail -2
kubeadm token create --certificate-key "$CERT_KEY" --print-join-command > /tmp/control-plane-join-command.txt

# Copy kubeconfig for retrieval
cp /etc/kubernetes/admin.conf /tmp/kubeconfig
chmod 644 /tmp/kubeconfig

# Label first master
kubectl label node $(hostname -s) node-role.kubernetes.io/control-plane= --overwrite

# Restart CoreDNS
kubectl rollout restart deployment -n kube-system coredns

# =============================================================================
# Final validation - ensure critical components are operational
# =============================================================================
echo "==> Running final validation..."
FAILURES=0

# Check VIP
if ! ip addr show $${NETWORK_INTERFACE} | grep -q "$${VIP_ADDRESS}"; then
  echo "FAIL: VIP $${VIP_ADDRESS} not active"
  FAILURES=$((FAILURES + 1))
fi

# Check kubelet
if ! systemctl is-active kubelet >/dev/null 2>&1; then
  echo "FAIL: kubelet not running"
  FAILURES=$((FAILURES + 1))
fi

# Check Calico (at least 1 pod running in calico-system)
CALICO_PODS=$(kubectl get pods -n calico-system --no-headers 2>/dev/null | grep -c Running || echo "0")
if [ "$CALICO_PODS" -lt 1 ]; then
  echo "FAIL: Calico not running ($CALICO_PODS pods)"
  FAILURES=$((FAILURES + 1))
fi

# Check MetalLB (at least 2 pods: controller + speaker)
METALLB_PODS=$(kubectl get pods -n metallb-system --no-headers 2>/dev/null | grep -c Running || echo "0")
if [ "$METALLB_PODS" -lt 2 ]; then
  echo "FAIL: MetalLB not ready ($METALLB_PODS pods)"
  FAILURES=$((FAILURES + 1))
fi

# Check kubeadm config exists (cluster was initialized)
if [ ! -f /etc/kubernetes/admin.conf ]; then
  echo "FAIL: /etc/kubernetes/admin.conf missing"
  FAILURES=$((FAILURES + 1))
fi

if [ "$FAILURES" -gt 0 ]; then
  echo "ERROR: $FAILURES critical component(s) failed - NOT continuing to worker join"
  exit 1
fi

echo "==> All critical components validated successfully"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "==> [Master Init] First control plane initialized successfully"
echo "==> VIP: $${VIP_ADDRESS} (kube-vip ARP mode)"
echo "==> MetalLB Pool: ${metallb_ip_pool}"
echo "==> Dashboard: LoadBalancer via MetalLB"
echo ""

# =============================================================================
# Step 11: HTTPS File Server (kubeconfig, tokens, join commands)
# =============================================================================
echo "==> Setting up HTTPS file server..."

FILES_DIR="/tmp/k8s-files"
CERT_DIR="/tmp/k8s-certs"
mkdir -p "$FILES_DIR" "$CERT_DIR"

# Generate self-signed certificate with IP SAN
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout "$CERT_DIR/server.key" -out "$CERT_DIR/server.crt" -days 365 \
  -subj "/CN=k8s-master" \
  -addext "subjectAltName=IP:${master_ip}" 2>/dev/null

# Copy files to serve (cp instead of ln to avoid symlinks in tarball)
cp -f /etc/kubernetes/admin.conf "$FILES_DIR/kubeconfig"
cp -f /tmp/dashboard-token.txt "$FILES_DIR/dashboard-token.txt"
cp -f /tmp/worker-join-command.txt "$FILES_DIR/worker-join-command.txt"

# Create HTTPS server script
cat > "$CERT_DIR/https-server.py" << 'PYEOF'
import http.server
import ssl
import sys
import os
import tarfile
import threading
import signal
import time

FILES_DIR = "/tmp/k8s-files"
PID_FILE = "/tmp/k8s-certs/https-server.pid"

class K8sFileHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/download-all":
            self._serve_download_all()
        elif self.path == "/":
            self._serve_index()
        else:
            self._serve_file()

    def _serve_download_all(self):
        tar_path = "/tmp/k8s-files.tar.gz"
        try:
            with tarfile.open(tar_path, "w:gz") as tar:
                for f in os.listdir(FILES_DIR):
                    filepath = os.path.join(FILES_DIR, f)
                    if os.path.isfile(filepath) or os.path.islink(filepath):
                        tar.add(filepath, arcname=f)
            with open(tar_path, "rb") as f:
                data = f.read()
            self.send_response(200)
            self.send_header("Content-Type", "application/gzip")
            self.send_header("Content-Disposition", 'attachment; filename="k8s-files.tar.gz"')
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)
        except Exception as e:
            self.send_response(500)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(f"Error: {e}".encode())
            return
        def shutdown_server():
            time.sleep(2)
            try:
                pid = int(open(PID_FILE).read().strip())
                os.kill(pid, signal.SIGTERM)
            except Exception:
                pass
        threading.Thread(target=shutdown_server, daemon=True).start()

    def _serve_index(self):
        files = sorted(os.listdir(FILES_DIR))
        links = "".join(
            f'<li><a href="/{f}">{f}</a></li>' for f in files if os.path.isfile(os.path.join(FILES_DIR, f)) or os.path.islink(os.path.join(FILES_DIR, f))
        )
        html = f"""<!DOCTYPE html>
<html><head><title>K8s Cluster Files</title></head>
<body>
<h2>Kubernetes Cluster Files</h2>
<ul>{links}</ul>
<hr>
<p><a href="/download-all"><b>Download ALL (.tar.gz)</b></a> - server will auto-shutdown after this</p>
</body></html>"""
        data = html.encode()
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _serve_file(self):
        filename = self.path.lstrip("/")
        filepath = os.path.join(FILES_DIR, filename)
        if not os.path.exists(filepath) or not (os.path.isfile(filepath) or os.path.islink(filepath)):
            self.send_response(404)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"404 Not Found")
            return
        if filename == "kubeconfig":
            content_type = "application/octet-stream"
        elif filename.endswith(".txt"):
            content_type = "text/plain"
        else:
            content_type = "application/octet-stream"
        with open(filepath, "rb") as f:
            data = f.read()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Disposition", f'attachment; filename="{filename}"')
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, format, *args):
        print(f"[HTTPS] {self.client_address[0]} - {format % args}")

context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain(certfile="/tmp/k8s-certs/server.crt", keyfile="/tmp/k8s-certs/server.key")

# Write own PID for reliable self-shutdown
with open(PID_FILE, "w") as pf:
    pf.write(str(os.getpid()))

httpd = http.server.HTTPServer(("0.0.0.0", 8443), K8sFileHandler)
httpd.socket = context.wrap_socket(httpd.socket, server_side=True)

print("==> HTTPS file server started on https://0.0.0.0:8443")
print("==> Available files:")
for f in sorted(os.listdir(FILES_DIR)):
    print(f"    https://{sys.argv[1]}:8443/{f}")
print(f"    https://{sys.argv[1]}:8443/download-all  (all files + auto-shutdown)")
print("==> Press Ctrl+C to stop")

httpd.serve_forever()
PYEOF

# Start server in background (Python writes its own PID to PID_FILE)
nohup python3 "$CERT_DIR/https-server.py" "${master_ip}" > "$CERT_DIR/https-server.log" 2>&1 &

# Verify server started (wait for PID file to be written)
sleep 2
if [ -f "$CERT_DIR/https-server.pid" ]; then
  HTTPS_PID=$(cat "$CERT_DIR/https-server.pid")
  if kill -0 $HTTPS_PID 2>/dev/null; then
    echo "==> HTTPS File Server running at https://${master_ip}:8443 (PID: $HTTPS_PID)"
  else
    echo "WARN: HTTPS server PID exists but process not running"
  fi
else
  echo "WARN: HTTPS server failed to start. Check $CERT_DIR/https-server.log"
fi
echo ""
echo "==> Download ALL files at once (server auto-shutdowns after):"
echo "    curl --insecure https://${master_ip}:8443/download-all -o k8s-files.tar.gz"
echo ""
echo "==> Or browse https://${master_ip}:8443/ for individual files"
echo ""
echo "==> Contents: kubeconfig, dashboard-token.txt, worker-join-command.txt"
echo ""
