#!/bin/bash
# =============================================================================
# Master Join - Additional Control Plane Nodes
# Generated by Terraform - Do not edit manually
# =============================================================================
set -euo pipefail

echo "==> [Master Join] Joining as control plane node"

# Wait for cloud-init
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
  echo "Waiting for cloud-init..."
  sleep 5
done

# =============================================================================
# Step 1: Install kube-vip static pod for HA VIP
# =============================================================================
echo "==> [VIP/HA] Installing kube-vip on additional control plane..."

VIP_ADDRESS="${vip_address}"
KVVERSION="v1.1.2"

# Detect the primary network interface
NETWORK_INTERFACE=$(ip route show default | awk '{print $5}' | head -1)
echo "==> Detected network interface: $NETWORK_INTERFACE"

# Pre-pull kube-vip image
echo "==> [VIP/HA] Pre-pulling kube-vip $${KVVERSION} image..."
crictl pull ghcr.io/kube-vip/kube-vip:$${KVVERSION} 2>&1 || echo "WARN: kube-vip image pull failed, will retry at runtime"

# Generate kube-vip static pod manifest (official ARP format)
mkdir -p /etc/kubernetes/manifests
cat > /etc/kubernetes/manifests/kube-vip.yaml << KVEOF
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: $${NETWORK_INTERFACE}
    - name: vip_subnet
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: address
      value: $${VIP_ADDRESS}
    image: ghcr.io/kube-vip/kube-vip:$${KVVERSION}
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/control-plane
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
KVEOF

echo "==> [VIP/HA] kube-vip manifest created with version $${KVVERSION}"

# =============================================================================
# Step 2: Wait for and validate join command from first master
# =============================================================================
echo "==> Waiting for control-plane join command from first master..."
for i in $(seq 1 30); do
  if [ -f /tmp/control-plane-join-command.txt ] && [ -s /tmp/control-plane-join-command.txt ]; then
    echo "==> Join command found"
    break
  fi
  echo "==> Waiting for join command (attempt $i/30)..."
  sleep 10
done

if [ ! -f /tmp/control-plane-join-command.txt ] || [ ! -s /tmp/control-plane-join-command.txt ]; then
  echo "ERROR: control-plane-join-command.txt not found or empty after 5 minutes"
  echo "The first master may not have finished kubeadm init yet"
  exit 1
fi

# =============================================================================
# Step 3: Join cluster as control plane
# =============================================================================
echo "==> Joining cluster as control plane..."
JOIN_CMD=$(cat /tmp/control-plane-join-command.txt | tr -d '\n')
$JOIN_CMD --cri-socket unix:///var/run/crio/crio.sock

# =============================================================================
# Step 4: Configure kubectl
# =============================================================================
echo "==> Configuring kubectl..."
mkdir -p /home/ubuntu/.kube
cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
chown 1000:1000 /home/ubuntu/.kube/config

mkdir -p /root/.kube
cp /etc/kubernetes/admin.conf /root/.kube/config

# Label this node
kubectl label node $(hostname -s) node-role.kubernetes.io/control-plane= --overwrite

echo "==> [Master Join] Successfully joined as control plane node (VIP: $${VIP_ADDRESS})"
