#!/bin/bash
# =============================================================================
# Worker Join - Joins worker nodes to the cluster
# Generated by Terraform - Do not edit manually
# =============================================================================
set -euo pipefail

echo "==> [Worker Join] Joining cluster as worker node"

# Wait for cloud-init
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
  echo "Waiting for cloud-init..."
  sleep 5
done

# Execute join (join command file was uploaded by Terraform)
echo "==> Joining cluster as worker..."
JOIN_CMD=$(cat /tmp/worker-join-command.txt | tr -d '\n')
$JOIN_CMD --cri-socket unix:///var/run/crio/crio.sock

# Wait for kubelet to register
sleep 10

echo "==> [Worker Join] Successfully joined as worker node"
